### DISCUSSION TITLE
Is there a REST / JSON API?

### DISCUSSION THREAD

**Discussion by hummelmose** [gnmyt/MySpeed#1009] [General]
Hi there.

Great little tool. Is there a API that I can call from Homey to use it there ?

Vielen dank :-)

**Comment by josephgeorgep** [comment]
even I was looking for something similar to get it integrated with HassIO :)

**Reply by twistedsanity** [reply]
https://github.com/gnmyt/MySpeed/issues/722#issuecomment-2184954461

**Comment by josephgeorgep** [comment]
Thanks @twistedsanity ! It helped
I was able to pull all the three sensors which I needed via Prometheus metrics. Giving my config here incase it helps anyone! :)

```yaml
sensor:
  - platform: rest
    name: "MySpeed Ping"
    resource: "http://yourip:port/api/prometheus/metrics"
    scan_interval: 300  # Update every 5 minutes
    value_template: >
      {% for line in value.split('\n') %}
        {% if 'myspeed_ping' in line and not line.startswith('#') %}
          {{ line.split()[1] }}
        {% endif %}
      {% endfor %}
    unit_of_measurement: "ms"

  - platform: rest
    name: "MySpeed Download Speed"
    resource: "http://yourip:port/api/prometheus/metrics"
    value_template: >
      {% for line in value.split('\n') %}
        {% if 'myspeed_download' in line and not line.startswith('#') %}
          {{ line.split()[1] }}
        {% endif %}
      {% endfor %}
    unit_of_measurement: "Mbps"

  - platform: rest
    name: "MySpeed Upload Speed"
    resource: "http://yourip:port/api/prometheus/metrics"
    value_template: >
      {% for line in value.split('\n') %}
        {% if 'myspeed_upload' in line and not line.startswith('#') %}
          {{ line.split()[1] }}
        {% endif %}
      {% endfor %}
    unit_of_measurement: "Mbps"
```
