### ISSUE TITLE
[Feature] Ability to deploy it under a subdirectory

### ISSUE THREAD

**Issue by luizkowalski** [gnmyt/MySpeed#771]
### General

- [X] My feature does not exist in the latest version of MySpeed.
- [X] I have checked that my feature has not been suggested by anyone else.

### Your Idea

Hey

I have a server with Traefik running and some containers under it. While most of these services allow a deployment under traefik.server/container, MySpeed doesn't and can't find assets.

This is my current Traefik setup:

```yaml
internet_speed:
  image: germannewsmaker/myspeed:1.0.9
  # port: 5216
  host: homeserver
  directories:
    - data:/myspeed/data
  labels:
    traefik.enable: true
    traefik.http.routers.internet_speed.rule: Host(`homeserver.local`) && PathPrefix(`/internet_speed`)
    traefik.http.routers.internet_speed.service: homeserver-internet-speed@docker
```
On the Inspector you can see that since there is no configuration available to let MySpeed know that it is running on a subdir, it tries to load assets from the root:

<img width="946" alt="image" src="https://github.com/user-attachments/assets/bbd97112-345f-4ff0-86ec-5ab1dea64ef5">

it would be nice to have something like an env var that I could set and all requests are prepended with this value, in this case, `internet_speed`, so that it runs on Traefik smoothly
