### ISSUE TITLE
[Bug] Request failed with status code 400

### ISSUE THREAD

**Issue by ChyiYaqing** [gnmyt/MySpeed#838]
### General

- [X] I have updated to the latest version of MySpeed.
- [X] My bug has not been reported yet.

### The Bug

Start myspeed using docker-compose and query the container log as follows.

```log
➜ docker logs -f myspeed
Successfully connected to the database file
Integration "discord" loaded successfully
Integration "gotify" loaded successfully
Integration "healthChecks" loaded successfully
Integration "pushover" loaded successfully
Integration "telegram" loaded successfully
Integration "webhook" loaded successfully
Looking for network interfaces...
An error occurred: Request failed with status code 400
Successfully connected to the database file
An error occurred: Request failed with status code 400
Successfully connected to the database file
```

docker-compose.yaml file contents are as follows.

```yaml
version: '3.9'
services:
  myspeed:
    image: germannewsmaker/myspeed
    container_name: "myspeed"
    ports:
      - 5216:5216
    volumes:
      - ./data:/myspeed/data
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "5M"
        max-file: "10"

networks:
  myspeed:
    driver: bridge
```

### What device are you using to access the page?

In the browser

### Which operating system is your MySpeed instance running on?

Linux
