### ISSUE TITLE
[Bug] Freshly created docker container not starting

### ISSUE THREAD

**Issue by bobvmierlo** [gnmyt/MySpeed#887]
### General

- [X] I have updated to the latest version of MySpeed.
- [X] My bug has not been reported yet.

### The Bug

On a fresh created docker container using the docker compose file below, the container won't start properly and shows the errors below from the log file. Portainer does not show logs at all.
Other docker containers on this machine run perfectly fine.

Errors from /data/logs/error.log:
```
## 11/8/2024, 10:19:50 PM
AxiosError: Request failed with status code 403
## 11/8/2024, 10:21:43 PM
AxiosError: Request failed with status code 403
## 11/8/2024, 10:21:44 PM
AxiosError: Request failed with status code 403
## 11/8/2024, 10:21:45 PM
AxiosError: Request failed with status code 403
## 11/8/2024, 10:21:47 PM
AxiosError: Request failed with status code 403
## 11/8/2024, 10:21:48 PM
AxiosError: Request failed with status code 403
## 11/8/2024, 10:21:51 PM
AxiosError: Request failed with status code 403
## 11/8/2024, 10:21:55 PM
AxiosError: Request failed with status code 403
```

Docker compose:
```yaml
name: myspeed
services:
    myspeed:
        ports:
            - 5216:5216
        volumes:
            - ./data:/myspeed/data
        restart: unless-stopped
        container_name: MySpeed
        image: germannewsmaker/myspeed
```

### What device are you using to access the page?

In the browser

### Which operating system is your MySpeed instance running on?

Linux
