### ISSUE TITLE
[Feature] Allow use as non-root

### ISSUE THREAD

**Issue by OddMagnet** [gnmyt/MySpeed#941]
### General

- [X] My feature does not exist in the latest version of MySpeed.
- [X] I have checked that my feature has not been suggested by anyone else.

### Your Idea

I generally like running my docker containers as non-root by providing by using the `user` attribute in my compose files:
```
user: ${PUID}:${PGID}
``` 

Even though I've create the necessary folders for myspeed, it still crashes with the error that it can't create the already existing `data` folder.

Would be cool if it could run as non-root

**Comment by toomyem** [comment]
It fails on creating `bin` directory. As a workaround, I added `RUN mkdir -m777 /myspeed/bin` to `Dockerfile`.

That way I can run it via `docker ... -u 1000:1000` and it works.

**Comment by thyrlian** [comment]
It's a nice and convenient image.

I also prefer not to run this type of service as `root` in my homelab. For a service like this, running as root feels unnecessary and increases the security risk, especially when bind-mounting host directories.

For anyone who wants to run MySpeed **as a non-root user without modifying or rebuilding the image**, the following workaround worked for me.

The important part is that MySpeed needs write access not only to `/myspeed/data`, but also to `/myspeed/bin`. If `/myspeed/bin` is not writable, the container may fail during startup with a misleading data-folder permission error.

On the host:
```bash
sudo mkdir -p <HOST_APP_PATH>/data
sudo mkdir -p <HOST_APP_PATH>/bin
sudo chown -R <UID>:<GID> <HOST_APP_PATH>
sudo chmod -R 775 <HOST_APP_PATH>
```

Then in `docker-compose.yml`:
```yaml
services:
  myspeed:
    image: germannewsmaker/myspeed:latest
    user: "<UID>:<GID>"
    volumes:
      - <HOST_APP_PATH>/data:/myspeed/data:rw
      - <HOST_APP_PATH>/bin:/myspeed/bin:rw
```

With the extra `/myspeed/bin` bind mount, MySpeed starts successfully as a non-root user.
